In [1]:
%load_ext autoreload
%autoreload 2

# Juegue un poco para ganar intuición

https://cardgames.io/reversi/

Aca le proponemos una pagina donde puede jugar para ganar intuición en el juego

Note que:
- En el tablero de 8x8 no resulta trivial una estrategia para ganar.
- Luego de jugar un rato podrá notar que ganar las esquinas y/o los bordes puede ser una buena estrategia

# Importar entorno y familiarizarse

In [2]:
from boardgame2 import ReversiEnv
import numpy as np

### Instanciación y reset

In [3]:
board_shape = 8
env = ReversiEnv(board_shape=board_shape)
(board, player) = env.reset()
print(board)
print(player)

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
1


### Jugadas válidas

In [4]:
env.get_valid((board, player))

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

### Pasos

In [5]:
(board, player), reward, done, _ = env.step([2,4])
print(board, player, done)

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]] -1 False


# Implementar una partida completa

Muestreando el esapcio de acción con env.action_space.sample (uniformemente)

Notar que el estado es (board, player)

In [6]:
done = False
# Resetear el entorno
(board, player) = env.reset()
while not done: # Mientras que el episodio no termine, ejecutar
    action = env.action_space.sample() # Muestrear acciones uniformemente
    print(board)
    print(f'acion: {action}')
    
    print(f'player: {player}')
    (board, player), reward, done, _ = env.step(action) # Ejecutar un paso
    

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
acion: (array([2, 7], dtype=int8),)
player: 1


In [7]:
board

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

Notar que muestrar uniformemente es un problema por que el episodio termina enseguida por la alta probabilidad de muestrar una acción no válida

# Implementar sample_valid_actions que muestrea uniformemente las acciones válidas

In [8]:
def sample_valid_actions(state, player):
    
    valid_actions = np.argwhere(env.get_valid((state, player)) == 1) 
    sampled_valid_action = valid_actions[np.random.randint(len(valid_actions))]
    return sampled_valid_action

In [24]:
np.argwhere(env.get_valid((board, player)) == 1)

array([[2, 4],
       [3, 5],
       [4, 2],
       [5, 3]])

In [10]:
# Verificar que funcione OK
sample_valid_actions(board, player)

array([2, 4])

### Correr ahora muestrando las acciones válidas y verificar que los epidosiod terminan en una situación donde ningún jugador puede mover mas

In [44]:
done = False
(board, player) = env.reset()
while not done:
    action = sample_valid_actions(board, player)
    print(board)
    print(f'acion: {action}')
    
    print(f'player: {player}')
    (board, player), reward, done, _ = env.step(action)

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
acion: [4 2]
player: 1
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  1  1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
acion: [5 2]
player: -1
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  1 -1  1  0  0  0]
 [ 0  0 -1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
acion: [3 5]
player: 1
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1  1  1  0  0]
 [ 0  0  1 -1  1  0  0  0]
 [ 0  0 -1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
acion: [4 1]
player: -1
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0 